/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2016-10-23 10:10:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_005fFetch_005fdatabase_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>AJAX JsonArray Example</title>\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("table, td, th\r\n");
      out.write("{\r\n");
      out.write("border:1px solid green;\r\n");
      out.write("font-family: 'Oxygen', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("th\r\n");
      out.write("{\r\n");
      out.write("background-color:green;\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write("body\r\n");
      out.write("{\r\n");
      out.write(" text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".container\r\n");
      out.write("{\r\n");
      out.write(" margin-left: auto;\r\n");
      out.write(" margin-right: auto;\r\n");
      out.write(" width: 40em;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write(" $(\"#tablediv\").hide();\r\n");
      out.write("     $(\"#showTable\").click(function(event){\r\n");
      out.write("           $.get('PopulateTable',function(responseJson) {\r\n");
      out.write("            if(responseJson!=null){\r\n");
      out.write("                $(\"#countrytable\").find(\"tr:gt(0)\").remove();\r\n");
      out.write("                var table1 = $(\"#countrytable\");\r\n");
      out.write("                $.each(responseJson, function(key,value) { \r\n");
      out.write("                     var rowNew = $(\"<tr><td></td><td></td><td></td><td></td><td></td><td></td></tr>\");\r\n");
      out.write("                        rowNew.children().eq(0).text(value['code']); \r\n");
      out.write("                        rowNew.children().eq(1).text(value['name']); \r\n");
      out.write("                        rowNew.children().eq(2).text(value['continent']); \r\n");
      out.write("                        rowNew.children().eq(3).text(value['region']); \r\n");
      out.write("                        rowNew.children().eq(4).text(value['population']); \r\n");
      out.write("                        rowNew.children().eq(5).text(value['capital']); \r\n");
      out.write("                        rowNew.appendTo(table1);\r\n");
      out.write("                });\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("            $(\"#tablediv\").show();          \r\n");
      out.write("  });      \r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"container\">\r\n");
      out.write("<h1>AJAX Retrieve Data from Database in Servlet and JSP using JSONArray</h1>\r\n");
      out.write("<input type=\"button\" value=\"Show Table\" id=\"showTable\"/>\r\n");
      out.write("<div id=\"tablediv\">\r\n");
      out.write("<table cellspacing=\"0\" id=\"countrytable\"> \r\n");
      out.write("    <tr> \r\n");
      out.write("        <th scope=\"col\">Code</th> \r\n");
      out.write("        <th scope=\"col\">Name</th> \r\n");
      out.write("        <th scope=\"col\">Continent</th> \r\n");
      out.write("        <th scope=\"col\">Region</th> \r\n");
      out.write("        <th scope=\"col\">Population</th> \r\n");
      out.write("        <th scope=\"col\">Capital</th>          \r\n");
      out.write("    </tr> \r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
